# The URL the site will be built for
base_url = "https://jskaza.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site title and description; they are used in feeds by default.
title = "Jonathan Skaza"
description = "Academic CV and Portfolio"

# The default language; used in feeds and search index
# Note that the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# The theme to use for syntax highlighting
# Theme options can be found at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
# highlight_code = true
# highlight_theme = "base16-ocean-dark"

# When set to "true", the generated HTML files are minified.
minify_html = false

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# ignored_content = ["*.{graphml,xlsx}"]

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Personal information
name = "Jonathan Skaza"
role = "PhD Student"
organization = "University of California, Santa Barbara"
location = "Santa Barbara, CA"
email = "skaza@ucsb.edu"
# Bio/about section
bio = """
I am a PhD student studying [Mind and Machine Intelligence](https://mind-machine.ucsb.edu) in the [Vision and Image Understanding Lab](https://viu.psych.ucsb.edu/) and [Dynamical Neuroscience](https://www.dyns.ucsb.edu/) program at UC Santa Barbara.
Previously, I worked as a Computational Science Developer in the [Cowley Group](http://cowleygroup.cshl.edu/) at [Cold Spring Harbor Laboratory](https://www.cshl.edu/). Prior to that, I served as a Solutions Analyst and subsequently Associate Director of Product in industry at [Panalgo](https://panalgo.com/). I received my MS in Biostatistics from the [University of Michigan](https://sph.umich.edu/biostat/), during which I worked with the Department of Psychiatry, and BS with a double major in Applied Economics and Applied Mathematics & Statistics from [Bryant University](https://www.bryant.edu/).
"""
interests = ["NeuroAI", "Machine Perception", "Computational Neuroscience", "Artificial Intelligence"]

# Education entries
[[extra.education]]
degree = "PhD Student in Computational Neuroscience"
institution = "University of California, Santa Barbara"

[[extra.education]]
degree = "MSc in Biostatistics"
institution = "University of Michigan"


[[extra.education]]
degree = "BSc in Applied Mathematics & Statistics, Applied Economics"
institution = "Bryant University"


# Social links
[[extra.social]]
name = "Email"
url = "mailto:skaza@ucsb.edu"
icon = "fas fa-envelope"

[[extra.social]]
name = "X"
url = "https://x.com/JonSkaza"
icon = "fa-brands fa-x-twitter"

[[extra.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=dAAMOqgAAAAJ&hl=en"
icon = "ai ai-google-scholar"

[[extra.social]]
name = "GitHub"
url = "https://github.com/jskaza"
icon = "fab fa-github"

[[extra.social]]
name = "LinkedIn"
url = "https://linkedin.com/in/jonskaza"
icon = "fab fa-linkedin"

[[extra.menu]]
name = "Publications"
url = "/publications/"
weight = 1

[[extra.menu]]
name = "Conferences"
url = "/conferences/"
weight = 2






# Features to enable
enable_dark_mode = true
enable_search = false
