name: Update Publications and CV

on:
  schedule:
    # Run weekly on Sundays at 8:00 AM UTC
    - cron: '0 8 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-publications-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        pip install scholarly tomli-w tqdm
        
    - name: Set up Typst
      uses: typst-community/setup-typst@v3
      with:
        typst-version: latest
        
    - name: Fetch publications from Google Scholar
      run: |
        python scripts/fetch_pubs.py
        
    - name: Compile CV with Typst
      run: |
        typst compile --root . static/cv/cv.typ
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update publications and CV [skip ci]"
        git push 