name: update publications

on:
  schedule:
    # Run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-20.04  # Using a more stable version
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Set up TinyTeX
      uses: r-lib/actions/setup-tinytex@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libpng-dev libuv1-dev

    - name: Check internet connectivity
      run: curl -I https://cloud.r-project.org || exit 1

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ~/.local/share/R
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-r-

    - name: Install R dependencies individually
      run: |
        options(repos = c(CRAN = "https://cloud.r-project.org"))
        install_list <- c("scholar", "tidyverse", "lubridate", "here")
        for (pkg in install_list) {
          for (i in 1:3) {
            tryCatch({
              install.packages(pkg)
              break
            }, error = function(e) {
              if (i == 3) stop(paste("Package", pkg, "installation failed after 3 attempts"))
              Sys.sleep(10)
            })
          }
        }
      shell: Rscript {0}

    - name: Run R script
      run: Rscript RScripts/update_all.R

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --quiet HEAD; then
          git commit -m "Update publications data [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
