name: Update Publications Monthly

on:
  schedule:
    # Run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
    
    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("scholar", "tidyverse", "lubridate", "here"), repos="https://cloud.r-project.org")'
    
    - name: Run R script
      run: |
        Rscript RScripts/update_all.R
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update publications data [skip ci]" && git push) 